### ISSUE TITLE
Disappearing network share - Netgear D7800 v21.02

### ISSUE THREAD

**Issue by olekstomek** [namjaejeon/ksmbd#383]
I am adding a problem found [on the forum (Polish language)](https://eko.one.pl/forum/viewtopic.php?id=21544) that has not been reported here.
My loose translation:

_Compilation downloaded from the forum from luci. Attached NTFS drive. The share runs for 10-60 minutes after restart.
Later it stops working and is unavailable. I can browse from CLI via SSH but on 2 computers with Win10 share it becomes unavailable. Restarting the router helps.
The only thing I can see in the logs is:
SysLog:_

> Thu Oct 28 19:26:50 2021 daemon.err odhcp6c[1624]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)
> Thu Oct 28 19:27:31 2021 kern.err kernel: [  314.609830] ksmbd: parse_sec_desc:814: parse_sec_desc: Error -22 mapping Owner SID to uid
> Thu Oct 28 19:27:31 2021 kern.err kernel: [  314.609860] ksmbd: parse_sec_desc:829: parse_sec_desc: Error -22 mapping Group SID to gid
> Thu Oct 28 19:28:48 2021 daemon.err odhcp6c[1624]: Failed to send SOLICIT message to ff02::1:2 (Permission denied)

Kernel Log:

> [  314.609860] ksmbd: parse_sec_desc:829: parse_sec_desc: Error -22 mapping Group SID to gid
> [ 3101.260181] ksmbd: __ipc_heartbeat:835: No IPC daemon response for 20s

_I observe the same behavior when connected via eSATA and USB3.0._

The original post is available at the forum link provided above.

**Comment by egc112** [comment]
Users on the DDWRT forum report the same behaviour:
https://forum.dd-wrt.com/phpBB2/viewtopic.php?t=330565&start=30

**Comment by mmakassikis** [comment]
Hello,
 
> [ 3101.260181] ksmbd: __ipc_heartbeat:835: No IPC daemon response for 20s

This suggests the userland process (ksmbd.mountd) is either dead or not responding. Since this process is the one that handles session authentication/share enumeration/..., it would explain why the user can no longer access the shares.

Rather than rebooting the router, the user can try restarting the ksmbd.mountd process (I don't know the specifics of OpenWRT/DD-WRT so the service may be named differently)

It would be interesting to know:
 - does restarting ksmbd.mountd restore access ?
 - was ksmbd.mountd running or crashed ?
 - are there any logs from the previous process which would explain why it crashed / hung ?
 - what's the exact version of ksmbd.mountd that is used ? I recall there were some issues with earlier versions.
 - the config file may be helpful to attempt reproduce the issue

**Comment by namjaejeon** [comment]
Thanks for comment, Marios,

@olekstomek luci ? Where is the problem coming from? openWRT or dd-wrt ?

> [ 3101.260181] ksmbd: __ipc_heartbeat:835: No IPC daemon response for 20s

It seems that ksmbd.mount is dead. As I know, dd-wrt use own ksmbd.mountd(i.e. not to use glib library)
It mean ksmbd.mountd of dd-wrt is not mainline version.
We need to check why ksmbd.mount is dead. coredump or other debugging. and if ksmbd.mountd is not mainline version, we may not to help you.

**Comment by olekstomek** [comment]
> Where is the problem coming from? openWRT or dd-wrt ?

OpenWrt.

Unfortunately I am unable to answer other questions or write details. This is not my problem and it is a problem that I found on that forum.

**Comment by olekstomek** [comment]
Update (my translation from Polish language [this original post](https://eko.one.pl/forum/viewtopic.php?pid=259927#p259927)):

> For me, it turned out that the problem is the eSATA/USB, namely it has a strange power saving mode built in. After disabling this, share works flawlessly so far.

The problem has been resolved and is not due to ksmbd error. But I believe that the report was worth attention and will be of use in similar problems.
I'm closing this issues for the moment.
